# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff2bc02da06c297514468312c51485e3fd243c7bdd2ce5e67ec08991bda82be5cc26996433d549784eabfa202ac3210b528e4d4712f6a55d7f6988e65068c274

test:
  secret_key_base: a21f598773dc6770168972faa125e2c01d2a9f5f422289780fd4e4dfd2ffe73f06a1289f178830f6d2667403ce98c4f11b77342b7cbe23c05ad467aaaf7345db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
